apiVersion: v1
kind: Pod
metadata:
  name: fortune5s
  labels:
    name: fortune5s
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    ports:
      - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html #nginx이 index.html default 동작
  - name: html-generator
    args: ["5"]
    image: parkian/fortuneloop
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
