apiVersion: v1
kind: Pod
metadata:
  name: nginx-configvol
spec:
  containers:
  - image: nginx:1.7.9
    name: web-server
    volumeMounts:
    - name: config
      #변경하고 싶은 파일명 적어주면 됨 -> 
      mountPath: /etc/nginx/conf.d/default.conf #default directory를 덮어쓰는 것이 아닌 default.conf 파일을 덮어씀
      subPath: custom-nginx-config.conf # 주의 : configmap 의 key 와 파일명이 일치 해야합니다. 파일 하나 바꿈
      readOnly: true
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: config
    configMap:
      name: fortune-config
      defaultMode: 0660